spring.application.name=clinic-bot
server.port=8090

spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/clinic-realm}
spring.security.oauth2.client.registration.clinic-bot.client-id=clinic-bot-service
spring.security.oauth2.client.registration.clinic-bot.client-secret=${KEYCLOAK_CLIENT_SECRET:MnRm2WcQMWruSA09qH2jpL9dwwF45ijx}
spring.security.oauth2.client.registration.clinic-bot.authorization-grant-type=client_credentials
spring.security.oauth2.client.registration.clinic-bot.provider=keycloak
spring.security.oauth2.client.provider.keycloak.issuer-uri=${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/clinic-realm}

mqtt.broker=tcp://${MQTT_HOST:localhost}:${MQTT_PORT:1883}
mqtt.client-id=pet-analyzer-client
mqtt.topic=pet/anomalies

gateway.url=http://${GATEWAY_HOST:localhost}:${GATEWAY_PORT:8888}
service.appointment.url=${gateway.url}/api/appointment/tgUser/{tgUserId}
service.profile.url=${gateway.url}/api/profile/owner/tg-chat-id

vk.bot.token=vk1.a.5Tj8HTyKA7La2A8QP07NpSCaXzDrCYYiTNOvKPAkSxw1os_l7rsB-DIC_k2xs6zcSU8uTjYZxnOZd7ehjwnoH3RTcbZBgSVhpUQlvKZBl60lalyPltK2wQK6dAfvqGUlb78gz8Cxqr-x_otliWqr_ymt2gsLgNpmfgbN71B3FYE9pKzoUjwW08w5TQjjBbCvQeG5sW2EShOyOrHCaVgSEQ
vk.bot.group-id=238424384
vk.bot.api-version=5.199